---
# Variables listed here are applicable to all host groups

url_apt_key: "http://keyserver.ubuntu.com/pks/lookup?op=get&search="

ntpserver: '0.fr.pool.ntp.org'

user: lesmyrmidons
local_home: "{{ lookup('env','HOME') }}"

web:
  httpd_port: 80
  domain: adst.karbouin.net
  project_path: /home/lesmyrmidons/Project/dev/github/adst
  directory_index: app.php

php5:
  php_date_timezone: 'Europe/Paris'

mariadb:
  current_password: ''
  root_password: dev
