---

# Install custom vim
- name: VIM | Clone vim config
  sudo: false
  git: repo=git@github.com:lesmyrmidons/vim-config.git
       dest=/home/{{ user }}/.vim-config
       update=yes

- name: VIM | Created symlink (vimrc)
  sudo: false
  file: src=/home/{{ user }}/.vim-config/vimrc dest=/home/{{ user }}/.vimrc owner={{ user }} group={{ user }} state=link

- name: VIM | Created symlink (.vim/)
  sudo: false
  file: src=/home/{{ user }}/.vim-config/vim dest=/home/{{ user }}/.vim owner={{ user }} group={{ user }} state=link